create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  date text not null,
  time text not null,
  location text not null,
  image text,
  participants integer not null default 0,
  category text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  display_name text not null,
  email text not null unique,
  pin_hash text not null,
  role text not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_users_role_check check (role in ('user', 'admin'))
);

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  app_user_id bigint references public.app_users(id) on delete set null,
  player_name text not null,
  score integer not null,
  played_at timestamptz not null default now(),
  week_ref text not null
);

create table if not exists public.arcade_users (
  id bigint generated by default as identity primary key,
  app_user_id bigint unique references public.app_users(id) on delete set null,
  player_name text not null unique,
  xp integer not null default 0,
  arcade_credit integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.arcade_missions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.arcade_users(id) on delete cascade,
  mission_key text not null,
  title text not null,
  description text not null,
  current_progress integer not null default 0,
  target integer not null,
  completed boolean not null default false,
  reward_xp integer not null default 0,
  reward_credit integer not null default 0,
  week_ref text not null,
  expires_at timestamptz not null,
  completed_at timestamptz,
  unique(user_id, mission_key, week_ref)
);

create table if not exists public.arcade_coupons (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.arcade_users(id) on delete cascade,
  code text not null unique,
  discount_type text not null,
  discount_value integer not null,
  status text not null default 'unused',
  event_id bigint references public.events(id) on delete set null,
  source text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create table if not exists public.arcade_attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.arcade_users(id) on delete cascade,
  app_user_id bigint references public.app_users(id) on delete set null,
  run_id text not null unique,
  score integer not null,
  duration_ms integer not null,
  submitted_at timestamptz not null default now(),
  week_ref text not null
);

create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  status text not null,
  teams integer not null default 0,
  max_teams integer,
  date_label text not null,
  time text not null,
  location text not null,
  leader text,
  format text not null,
  description text not null,
  accent text,
  bracket jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.tournament_registrations (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  app_user_id bigint not null references public.app_users(id) on delete cascade,
  team_name text not null,
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(tournament_id, app_user_id)
);

alter table public.leaderboard add column if not exists app_user_id bigint references public.app_users(id) on delete set null;
alter table public.arcade_users add column if not exists app_user_id bigint unique references public.app_users(id) on delete set null;
alter table public.arcade_attempts add column if not exists app_user_id bigint references public.app_users(id) on delete set null;
alter table public.app_users add column if not exists role text not null default 'user';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'app_users_role_check'
      and conrelid = 'public.app_users'::regclass
  ) then
    alter table public.app_users
      add constraint app_users_role_check check (role in ('user', 'admin'));
  end if;
end $$;

-- Esempio: promuovi un profilo ad admin sostituendo l'email.
-- update public.app_users set role = 'admin' where email = 'admin@example.com';

create index if not exists events_date_time_idx on public.events(date, time);
create index if not exists leaderboard_week_score_idx on public.leaderboard(week_ref, score desc, played_at asc);
delete from public.leaderboard l
using (
  select
    id,
    row_number() over (
      partition by app_user_id, week_ref
      order by score desc, played_at asc, id asc
    ) as row_rank
  from public.leaderboard
  where app_user_id is not null
) ranked
where l.id = ranked.id
  and ranked.row_rank > 1;
create unique index if not exists leaderboard_app_user_week_unique_idx
  on public.leaderboard(app_user_id, week_ref)
  where app_user_id is not null;
create index if not exists arcade_attempts_user_week_idx on public.arcade_attempts(user_id, week_ref);
create index if not exists arcade_coupons_user_status_idx on public.arcade_coupons(user_id, status);
create index if not exists tournaments_slug_idx on public.tournaments(slug);
create index if not exists tournament_registrations_user_idx on public.tournament_registrations(app_user_id, tournament_id);

alter table public.app_users enable row level security;
alter table public.events enable row level security;
alter table public.leaderboard enable row level security;
alter table public.arcade_users enable row level security;
alter table public.arcade_missions enable row level security;
alter table public.arcade_coupons enable row level security;
alter table public.arcade_attempts enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_registrations enable row level security;

drop policy if exists "app users anon read" on public.app_users;
drop policy if exists "app users anon insert" on public.app_users;
drop policy if exists "app users anon update" on public.app_users;
drop policy if exists "events anon read" on public.events;
drop policy if exists "events anon insert" on public.events;
drop policy if exists "events anon update" on public.events;
drop policy if exists "events anon delete" on public.events;
drop policy if exists "leaderboard anon read" on public.leaderboard;
drop policy if exists "leaderboard anon insert" on public.leaderboard;
drop policy if exists "leaderboard anon update" on public.leaderboard;
drop policy if exists "arcade users anon read" on public.arcade_users;
drop policy if exists "arcade users anon insert" on public.arcade_users;
drop policy if exists "arcade users anon update" on public.arcade_users;
drop policy if exists "arcade missions anon read" on public.arcade_missions;
drop policy if exists "arcade missions anon insert" on public.arcade_missions;
drop policy if exists "arcade missions anon update" on public.arcade_missions;
drop policy if exists "arcade coupons anon read" on public.arcade_coupons;
drop policy if exists "arcade coupons anon insert" on public.arcade_coupons;
drop policy if exists "arcade coupons anon update" on public.arcade_coupons;
drop policy if exists "arcade attempts anon read" on public.arcade_attempts;
drop policy if exists "arcade attempts anon insert" on public.arcade_attempts;
drop policy if exists "tournaments anon read" on public.tournaments;
drop policy if exists "tournaments anon insert" on public.tournaments;
drop policy if exists "tournaments anon update" on public.tournaments;
drop policy if exists "registrations anon read" on public.tournament_registrations;
drop policy if exists "registrations anon insert" on public.tournament_registrations;
drop policy if exists "registrations anon update" on public.tournament_registrations;

create policy "app users anon read" on public.app_users for select to anon using (true);
create policy "app users anon insert" on public.app_users for insert to anon with check (true);
create policy "app users anon update" on public.app_users for update to anon using (true) with check (true);

create policy "events anon read" on public.events for select to anon using (true);
create policy "events anon insert" on public.events for insert to anon with check (true);
create policy "events anon update" on public.events for update to anon using (true) with check (true);
create policy "events anon delete" on public.events for delete to anon using (true);

create policy "leaderboard anon read" on public.leaderboard for select to anon using (true);
create policy "leaderboard anon insert" on public.leaderboard for insert to anon with check (true);
create policy "leaderboard anon update" on public.leaderboard for update to anon using (true) with check (true);

create policy "arcade users anon read" on public.arcade_users for select to anon using (true);
create policy "arcade users anon insert" on public.arcade_users for insert to anon with check (true);
create policy "arcade users anon update" on public.arcade_users for update to anon using (true) with check (true);

create policy "arcade missions anon read" on public.arcade_missions for select to anon using (true);
create policy "arcade missions anon insert" on public.arcade_missions for insert to anon with check (true);
create policy "arcade missions anon update" on public.arcade_missions for update to anon using (true) with check (true);

create policy "arcade coupons anon read" on public.arcade_coupons for select to anon using (true);
create policy "arcade coupons anon insert" on public.arcade_coupons for insert to anon with check (true);
create policy "arcade coupons anon update" on public.arcade_coupons for update to anon using (true) with check (true);

create policy "arcade attempts anon read" on public.arcade_attempts for select to anon using (true);
create policy "arcade attempts anon insert" on public.arcade_attempts for insert to anon with check (true);

create policy "tournaments anon read" on public.tournaments for select to anon using (true);
create policy "tournaments anon insert" on public.tournaments for insert to anon with check (true);
create policy "tournaments anon update" on public.tournaments for update to anon using (true) with check (true);

create policy "registrations anon read" on public.tournament_registrations for select to anon using (true);
create policy "registrations anon insert" on public.tournament_registrations for insert to anon with check (true);
create policy "registrations anon update" on public.tournament_registrations for update to anon using (true) with check (true);

insert into public.tournaments
  (slug, name, status, teams, max_teams, date_label, time, location, leader, format, description, accent, bracket)
values
  (
    'calcetto-estate',
    'Torneo Calcetto Estate',
    'Iscrizioni aperte',
    8,
    16,
    '15 Giu',
    '20:30',
    'Campo sportivo Forette',
    'Forette Blu',
    'Gironi + semifinali',
    'Partite serali da 20 minuti, squadre da 5 giocatori e finale durante la serata conclusiva.',
    'tournament-tone-1',
    '[{"title":"Semifinali","matches":[{"teamA":"Forette Blu","scoreA":3,"teamB":"San Pietro","scoreB":1},{"teamA":"I Solari","scoreA":2,"teamB":"Bar Centrale","scoreB":0}]},{"title":"Finale","matches":[{"teamA":"Forette Blu","scoreA":"-","teamB":"I Solari","scoreB":"-"}]},{"title":"Podio","matches":[{"teamA":"1° Forette Blu","scoreA":"","teamB":"2° I Solari","scoreB":""}]}]'::jsonb
  ),
  (
    'beach-volley',
    'Beach Volley in Piazza',
    'Semifinali',
    6,
    12,
    '22 Giu',
    '18:00',
    'Piazza centrale',
    'I Solari',
    'Eliminazione diretta',
    'Coppie miste, set ai 21 punti e rotazione rapida per tenere il torneo vivace fino alla finale.',
    'tournament-tone-2',
    '[{"title":"Quarti","matches":[{"teamA":"I Solari","scoreA":21,"teamB":"Volley Bar","scoreB":14},{"teamA":"Forette Beach","scoreA":18,"teamB":"Team Sprint","scoreB":21}]},{"title":"Semifinali","matches":[{"teamA":"I Solari","scoreA":"-","teamB":"Team Sprint","scoreB":"-"}]},{"title":"Finale","matches":[{"teamA":"Vincente SF1","scoreA":"","teamB":"Vincente SF2","scoreB":""}]}]'::jsonb
  ),
  (
    'burraco-sagra',
    'Burraco della Sagra',
    'Finale pronta',
    12,
    20,
    '29 Giu',
    '21:00',
    'Sala civica',
    'Coppia Neri',
    'Classifica a punti',
    'Tavoli sorteggiati, tre turni di qualificazione e finale tra le due coppie con punteggio migliore.',
    'tournament-tone-3',
    '[{"title":"Qualifica","matches":[{"teamA":"Coppia Neri","scoreA":1240,"teamB":"Coppia Rizzi","scoreB":980},{"teamA":"Coppia Blu","scoreA":1110,"teamB":"Coppia Festa","scoreB":1040}]},{"title":"Finale","matches":[{"teamA":"Coppia Neri","scoreA":"-","teamB":"Coppia Blu","scoreB":"-"}]},{"title":"Premi","matches":[{"teamA":"1° Buono cena","scoreA":"","teamB":"2° Cesto festa","scoreB":""}]}]'::jsonb
  )
on conflict (slug) do nothing;
